### ISSUE TITLE
Trying to use the test cases and getting an error when i execute:    python -m pytest

### ISSUE THREAD

**Issue by ptyo** [aws-samples/aws-billing-conductor-sp-ri-benefit-utility#5]
PS C:\Users\ptyo\Downloads\development\aws-billing-conductor-sp-ri-benefit-utility> python -m pytest
======================================================== test session starts ========================================================
platform win32 -- Python 3.12.7, pytest-8.3.3, pluggy-1.5.0
rootdir: C:\Users\ptyo\Downloads\development\aws-billing-conductor-sp-ri-benefit-utility
collected 7 items / 3 errors

============================================================== ERRORS ===============================================================
________________________________ ERROR collecting sam_sp_ri_utility/test/test_reserved_instances.py _________________________________
ImportError while importing test module 'C:\Users\ptyo\Downloads\development\aws-billing-conductor-sp-ri-benefit-utility\sam_sp_ri_utility\test\test_reserved_instances.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
..\..\..\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py:90: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
sam_sp_ri_utility\test\test_reserved_instances.py:2: in <module>
    from sam_sp_ri_utility.services.reserved_instances import *
sam_sp_ri_utility\services\reserved_instances.py:1: in <module>
    from .usage import *
sam_sp_ri_utility\services\usage.py:1: in <module>
    import boto3
E   ModuleNotFoundError: No module named 'boto3'
___________________________________ ERROR collecting sam_sp_ri_utility/test/test_savings_plans.py ___________________________________ 
ImportError while importing test module 'C:\Users\ptyo\Downloads\development\aws-billing-conductor-sp-ri-benefit-utility\sam_sp_ri_utility\test\test_savings_plans.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
..\..\..\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py:90: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
sam_sp_ri_utility\test\test_savings_plans.py:2: in <module>
    from sam_sp_ri_utility.services.savings_plans import *
sam_sp_ri_utility\services\savings_plans.py:1: in <module>
    from .usage import *
sam_sp_ri_utility\services\usage.py:1: in <module>
    import boto3
E   ModuleNotFoundError: No module named 'boto3'
_______________________________________ ERROR collecting sam_sp_ri_utility/test/test_usage.py _______________________________________ 
ImportError while importing test module 'C:\Users\ptyo\Downloads\development\aws-billing-conductor-sp-ri-benefit-utility\sam_sp_ri_utility\test\test_usage.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
..\..\..\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py:90: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
sam_sp_ri_utility\test\test_usage.py:1: in <module>
    from sam_sp_ri_utility.services.usage import *
sam_sp_ri_utility\services\usage.py:1: in <module>
    import boto3
E   ModuleNotFoundError: No module named 'boto3'
====================================================== short test summary info ====================================================== 
ERROR sam_sp_ri_utility/test/test_reserved_instances.py
ERROR sam_sp_ri_utility/test/test_savings_plans.py
ERROR sam_sp_ri_utility/test/test_usage.py
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 3 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! 
========================================================= 3 errors in 0.23s =========================================================

**Comment by ptyo** [comment]
Also when I run Unittest test discovery error for workspace:
2024-11-08 13:18:08.031 [info] Discover tests for workspace name: aws-billing-conductor-sp-ri-benefit-utility - uri: c:\Users\ptyo\Downloads\development\aws-billing-conductor-sp-ri-benefit-utility\sam_sp_ri_utility\test\test_usage.py
2024-11-08 13:18:08.031 [info] Running discovery for unittest using the new test adapter.
2024-11-08 13:18:08.050 [info] Discovering unittest tests for workspace c:\Users\ptyo\Downloads\development\aws-billing-conductor-sp-ri-benefit-utility with arguments: c:\Users\ptyo\.vscode\extensions\ms-python.python-2024.18.1-win32-x64\python_files\unittestadapter\discovery.py,--udiscovery,-v,-s,./sam_sp_ri_utility/,-p,test_*.py

2024-11-08 13:18:08.050 [info] > ~\AppData\Local\Programs\Python\Python310\python.exe ~\.vscode\extensions\ms-python.python-2024.18.1-win32-x64\python_files\unittestadapter\discovery.py --udiscovery -v -s ./sam_sp_ri_utility/ -p test_*.py
2024-11-08 13:18:08.050 [info] cwd: .
2024-11-08 13:18:08.248 [error] Unittest test discovery error for workspace:  c:\Users\ptyo\Downloads\development\aws-billing-conductor-sp-ri-benefit-utility 
 Failed to import test module: test.test_reserved_instances
Traceback (most recent call last):
  File "C:\Users\ptyo\AppData\Local\Programs\Python\Python310\lib\unittest\loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "C:\Users\ptyo\AppData\Local\Programs\Python\Python310\lib\unittest\loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "c:\Users\ptyo\Downloads\development\aws-billing-conductor-sp-ri-benefit-utility\sam_sp_ri_utility\test\test_reserved_instances.py", line 2, in <module>
    from sam_sp_ri_utility.services.reserved_instances import *
ModuleNotFoundError: No module named 'sam_sp_ri_utility'


Failed to import test module: test.test_savings_plans
Traceback (most recent call last):
  File "C:\Users\ptyo\AppData\Local\Programs\Python\Python310\lib\unittest\loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "C:\Users\ptyo\AppData\Local\Programs\Python\Python310\lib\unittest\loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "c:\Users\ptyo\Downloads\development\aws-billing-conductor-sp-ri-benefit-utility\sam_sp_ri_utility\test\test_savings_plans.py", line 2, in <module>
    from sam_sp_ri_utility.services.savings_plans import *
ModuleNotFoundError: No module named 'sam_sp_ri_utility'


Failed to import test module: test.test_usage
Traceback (most recent call last):
  File "C:\Users\ptyo\AppData\Local\Programs\Python\Python310\lib\unittest\loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "C:\Users\ptyo\AppData\Local\Programs\Python\Python310\lib\unittest\loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "c:\Users\ptyo\Downloads\development\aws-billing-conductor-sp-ri-benefit-utility\sam_sp_ri_utility\test\test_usage.py", line 1, in <module>
    from sam_sp_ri_utility.services.usage import *
ModuleNotFoundError: No module named 'sam_sp_ri_utility'

**Comment by ptyo** [comment]
Sorry tried a new machine and clean install... It is working as intended now... Sorry.

**Comment by ptyo** [comment]
Closed
